## ═══════════════════════════════════════════════
## VNV MAKER LIVE PREVIEW
## Scene: start
## Auto-generated by VNVMaker IDE — safe to delete
## ═══════════════════════════════════════════════

## Characters
define vnc_w90sbuoq = Character('Eileen', color='#ff99c2')
define vnc_fy591fhu = Character('System', color='#99ccff')

## Story Variables (auto-discovered)
default met_eileen = True

## Scenes
label vns_scene_ozdufg7g:
    scene expression Transform("gui/game_menu.png", fit="cover", xsize=config.screen_width, ysize=config.screen_height)
    "Welcome to VNV Maker! This is a generated demo project."
    vnc_w90sbuoq "Hi there! I am a character. You can edit me in the Characters tab."
    $ met_eileen = True
    menu:
        "What do you want to do now?"
        "See a good ending":
            jump vns_scene_pynfbawi
        "See a bad ending":
            jump vns_scene_8chcamkf
    return

label vns_scene_pynfbawi:
    vnc_w90sbuoq "You chose the good ending! Excellent choice."
    return

label vns_scene_8chcamkf:
    vnc_fy591fhu "CRITICAL ERROR. Just kidding. This is the bad end."
    return

## Preview Entry Point
## Bypasses the main menu so the game initializes properly into a play context.
label main_menu:
    return

define config.label_overrides = {"start": "vnv_preview_entry"}

label vnv_preview_entry:
    jump vns_scene_ozdufg7g
