## ═══════════════════════════════════════════════
## VNV MAKER LIVE PREVIEW
## Scene: Start
## Auto-generated by VNVMaker IDE — safe to delete
## ═══════════════════════════════════════════════

## Characters
define vnc_11tg9uyk = Character('Sylvie', color='#a78bfa')
define vnc_i4j3r1am = Character('Me', color='#c8c8ff')

## Scenes
label vns_scene_ns9gl3:
    scene expression Transform("bg uni.jpg", fit="cover", xsize=config.screen_width, ysize=config.screen_height)
    play music "audio/illurock.opus"
    play music "audio/illurock.opus"
    scene expression Transform("bg lecturehall.jpg", fit="cover", xsize=config.screen_width, ysize=config.screen_height)
    with Fade(0.5, 0.0, 0.5)
    "It's only when I hear the sounds of shuffling feet and supplies being put away that I realize that the lecture's over."
    "Professor Eileen's lectures are usually interesting, but today I just couldn't concentrate on it."
    "I've had a lot of other thoughts on my mind...thoughts that culminate in a question."
    "It's a question that I've been meaning to ask a certain someone."
    scene expression Transform("bg uni.jpg", fit="cover", xsize=config.screen_width, ysize=config.screen_height)
    with Fade(0.5, 0.0, 0.5)
    "When we come out of the university, I spot her right away."
    show expression "sylvie green normal.png" at center:
        xoffset -582
        yoffset -60
    with Dissolve(0.5)
    "I've known Sylvie since we were kids. She's got a big heart and she's always been a good friend to me."
    narrator "asdfhgaskijdehgfliakuwgherlfikauhwglef YOOOOOOOOOOOOOOOO"
    "narrator: But recently... I've felt that I want something more."
    "More than just talking, more than just walking home together when our classes end."
    menu:
        "As soon as she catches my eye, I decide..."
        "To ask her right away.":
            jump vns_scene_c5anxc
        "To ask her later.":
            jump vns_scene_nn5hep
    return

label vns_scene_c5anxc:
    scene expression Transform("bg meadow.jpg", fit="cover", xsize=config.screen_width, ysize=config.screen_height)
    show expression "sylvie green smile.png" at center
    vnc_11tg9uyk "Hi there! How was class?"
    vnc_i4j3r1am "Good..."
    "I can't bring myself to admit that it all went in one ear and out the other."
    vnc_i4j3r1am "Are you going home now? Wanna walk back with me?"
    show expression "sylvie green smile.png" at center
    vnc_11tg9uyk "Sure!"
    scene expression Transform("bg meadow.jpg", fit="cover", xsize=config.screen_width, ysize=config.screen_height)
    with Fade(0.5, 0.0, 0.5)
    "After a short while, we reach the meadows just outside the neighborhood where we both live."
    "It's a scenic view I've grown used to. Autumn is especially beautiful here."
    "When we were children, we played in these meadows a lot, so they're full of memories."
    vnc_i4j3r1am "Hey... Umm..."
    show expression "sylvie green smile.png" at center
    with Dissolve(0.5)
    "She turns to me and smiles. She looks so welcoming that I feel my nervousness melt away."
    "I'll ask her...!"
    vnc_i4j3r1am "Ummm... Will you..."
    vnc_i4j3r1am "Will you be my artist for a visual novel?"
    show expression "sylvie green surprised.png" at center
    "Silence."
    "She looks so shocked that I begin to fear the worst. But then..."
    show expression "sylvie green smile.png" at center
    menu:
        "Sure, but what's a \\\"visual novel\\\"?"
        "It's a videogame.":
            jump vns_scene_crd2p6
        "It's an interactive book.":
            jump vns_scene_68wp9a
    return

label vns_scene_crd2p6:
    vnc_i4j3r1am "It's a kind of videogame you can play on your computer or a console."
    vnc_i4j3r1am "Visual novels tell a story with pictures and music."
    vnc_i4j3r1am "Sometimes, you also get to make choices that affect the outcome of the story."
    show expression "sylvie green smile.png" at center
    vnc_11tg9uyk "So it's like those choose-your-adventure books?"
    vnc_i4j3r1am "Exactly! I've got lots of different ideas that I think would work."
    vnc_i4j3r1am "And I thought maybe you could help me...since I know how you like to draw."
    vnc_i4j3r1am "It'd be hard for me to make a visual novel alone."
    show expression "sylvie green normal.png" at center
    show expression "sylvie green normal.png" at center
    vnc_11tg9uyk "Well, sure! I can try. I just hope I don't disappoint you."
    vnc_i4j3r1am "You know you could never disappoint me, Sylvie."
    with Dissolve(0.5)
    with dissolve
    jump vns_scene_q77xtz
    return

label vns_scene_68wp9a:
    $ book = True
    vnc_i4j3r1am "It's like an interactive book that you can read on a computer or a console."
    show expression "sylvie green surprised.png" at center
    show expression "sylvie green surprised.png" at center
    vnc_11tg9uyk "Interactive?"
    vnc_i4j3r1am "You can make choices that lead to different events and endings in the story."
    show expression "sylvie green surprised.png" at center
    vnc_11tg9uyk "So where does the \\\"visual\\\" part come in?"
    vnc_i4j3r1am "Visual novels have pictures and even music, sound effects, and sometimes voice acting to go along with the text."
    show expression "sylvie green smile.png" at center
    show expression "sylvie green smile.png" at center
    vnc_11tg9uyk "I see! That certainly sounds like fun. I actually used to make webcomics way back when, so I've got lots of story ideas."
    vnc_i4j3r1am "That's great! So...would you be interested in working with me as an artist?"
    show expression "sylvie green smile.png" at center
    vnc_11tg9uyk "I'd love to!"
    with Dissolve(0.5)
    with dissolve
    jump vns_scene_q77xtz
    return

label vns_scene_q77xtz:
    scene expression Transform("bg club.jpg", fit="cover", xsize=config.screen_width, ysize=config.screen_height)
    scene expression Transform("bg club.jpg", fit="cover", xsize=config.screen_width, ysize=config.screen_height)
    with Dissolve(0.5)
    "And so, we become a visual novel creating duo."
    with Dissolve(0.5)
    "Over the years, we make lots of games and have a lot of fun making them."
    "We take turns coming up with stories and characters and support each other to make some great games!"
    "And one day..."
    show expression "sylvie blue normal.png" at center
    with Dissolve(0.5)
    show expression "sylvie blue normal.png" at center
    vnc_11tg9uyk "Hey..."
    vnc_i4j3r1am "Yes?"
    show expression "sylvie blue giggle.png" at center
    show expression "sylvie blue giggle.png" at center
    vnc_11tg9uyk "Will you marry me?"
    vnc_i4j3r1am "What? Where did this come from?"
    show expression "sylvie blue surprised.png" at center
    show expression "sylvie blue surprised.png" at center
    vnc_11tg9uyk "Come on, how long have we been dating?"
    vnc_i4j3r1am "A while..."
    show expression "sylvie blue normal.png" at center
    show expression "sylvie blue normal.png" at center
    vnc_11tg9uyk "These last few years we've been making visual novels together, spending time together, helping each other..."
    show expression "sylvie blue normal.png" at center
    vnc_11tg9uyk "I've gotten to know you and care about you better than anyone else. And I think the same goes for you, right?"
    vnc_i4j3r1am "Sylvie..."
    show expression "sylvie blue giggle.png" at center
    show expression "sylvie blue giggle.png" at center
    vnc_11tg9uyk "But I know you're the indecisive type. If I held back, who knows when you'd propose?"
    show expression "sylvie blue normal.png" at center
    show expression "sylvie blue normal.png" at center
    vnc_11tg9uyk "So will you marry me?"
    vnc_i4j3r1am "Of course I will! I've actually been meaning to propose, honest!"
    show expression "sylvie blue normal.png" at center
    vnc_11tg9uyk "I know, I know."
    vnc_i4j3r1am "I guess... I was too worried about timing. I wanted to ask the right question at the right time."
    show expression "sylvie blue giggle.png" at center
    show expression "sylvie blue giggle.png" at center
    vnc_11tg9uyk "You worry too much. If only this were a visual novel and I could pick an option to give you more courage!"
    with Dissolve(0.5)
    "We get married shortly after that."
    "Our visual novel duo lives on even after we're married...and I try my best to be more decisive."
    "Together, we live happily ever after even now."
    "{b}Good Ending{/b}."
    return

label vns_scene_nn5hep:
    "I can't get up the nerve to ask right now. With a gulp, I decide to ask her later."
    with Dissolve(0.5)
    "But I'm an indecisive person."
    "I couldn't ask her that day and I end up never being able to ask her."
    "I guess I'll never know the answer to my question now..."
    "{b}Bad Ending{/b}."
    return

## Preview Entry Point
## Bypasses the main menu so the game initializes properly into a play context.
label main_menu:
    return

define config.label_overrides = {"start": "vnv_preview_entry"}

label vnv_preview_entry:
    jump vns_scene_ns9gl3
